// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package bootstrap

import (
	"github.com/weplanx/server/api"
	"github.com/weplanx/server/api/departments"
	"github.com/weplanx/server/api/dsl"
	"github.com/weplanx/server/api/index"
	"github.com/weplanx/server/api/roles"
	"github.com/weplanx/server/api/sessions"
	"github.com/weplanx/server/api/users"
	"github.com/weplanx/server/api/values"
	"github.com/weplanx/server/utils/captcha"
	"github.com/weplanx/server/utils/locker"
)

// Injectors from wire.go:

func NewAPI() (*api.API, error) {
	commonValues, err := LoadStaticValues()
	if err != nil {
		return nil, err
	}
	client, err := UseMongoDB(commonValues)
	if err != nil {
		return nil, err
	}
	database := UseDatabase(commonValues, client)
	redisClient, err := UseRedis(commonValues)
	if err != nil {
		return nil, err
	}
	conn, err := UseNats(commonValues)
	if err != nil {
		return nil, err
	}
	jetStreamContext, err := UseJetStream(conn)
	if err != nil {
		return nil, err
	}
	transfer, err := UseTransfer(commonValues, jetStreamContext)
	if err != nil {
		return nil, err
	}
	hertz, err := UseHertz(commonValues)
	if err != nil {
		return nil, err
	}
	service := &sessions.Service{
		Values: commonValues,
		Redis:  redisClient,
	}
	rolesService := &roles.Service{
		Db: database,
	}
	departmentsService := &departments.Service{
		Db: database,
	}
	usersService := &users.Service{
		Values:             commonValues,
		Db:                 database,
		Redis:              redisClient,
		RolesService:       rolesService,
		DepartmentsService: departmentsService,
	}
	captchaCaptcha := &captcha.Captcha{
		Values: commonValues,
		Redis:  redisClient,
	}
	lockerLocker := &locker.Locker{
		Values: commonValues,
		Redis:  redisClient,
	}
	indexService := &index.Service{
		Values:             commonValues,
		SessionService:     service,
		UsersService:       usersService,
		RolesService:       rolesService,
		DepartmentsService: departmentsService,
		Captcha:            captchaCaptcha,
		Locker:             lockerLocker,
	}
	controller := &index.Controller{
		IndexService: indexService,
	}
	valuesService := &values.Service{
		Values: commonValues,
		Redis:  redisClient,
		Nats:   conn,
	}
	valuesController := &values.Controller{
		ValuesService: valuesService,
	}
	sessionsController := &sessions.Controller{
		SessionsService: service,
	}
	dslService := &dsl.Service{
		Db: database,
	}
	dslController := &dsl.Controller{
		DslService: dslService,
	}
	usersController := &users.Controller{
		UsersService: usersService,
	}
	apiAPI := &api.API{
		Values:            commonValues,
		Db:                database,
		Redis:             redisClient,
		Transfer:          transfer,
		Hertz:             hertz,
		IndexController:   controller,
		IndexService:      indexService,
		ValuesController:  valuesController,
		ValuesService:     valuesService,
		SessionController: sessionsController,
		SessionService:    service,
		DslController:     dslController,
		DslService:        dslService,
		UsersController:   usersController,
		UsersService:      usersService,
	}
	return apiAPI, nil
}
