package core

const model = `
// Code generated by bit. DO NOT EDIT.

package model

import (
	"gorm.io/gorm"
	"time"
)

{{range .}}
    type {{title .Key}} struct {
` +
	"ID     uint   `json:\"id\"`\n" +
	"Status     *bool      `gorm:\"default:true\" json:\"status\"`\n" +
	"CreateTime time.Time  `gorm:\"autoCreateTime\" json:\"create_time\"`\n" +
	"UpdateTime time.Time  `gorm:\"autoUpdateTime\" json:\"update_time\"`\n" +
	`{{range .Schema}}` +
	"{{title .Key}} {{typ .Type}} `{{tag .}}`\n" +
	`{{end}}
}
{{end}}

func AutoMigrate(tx *gorm.DB, models ...string) {
	mapper := map[string]interface{}{
		{{range .}}"{{ .Key}}": &{{title .Key}}{},{{end}}
	}

	for _, model := range models {
		if mapper[model] != nil {
			tx.AutoMigrate(mapper[model])
		}
	}
}
`
